<?php
/**
 * Plugin Name: wp_plugin
 * Plugin URI:  https://example.com/plugins/wp-plugin
 * Description: A lightweight WordPress plugin scaffold (generated by Copilot).
 * Version:     0.1.0
 * Author:      Your Name
 * Author URI:  https://example.com
 * Text Domain: wp-plugin
 * Domain Path: /languages
 * License:     MIT
 */

declare(strict_types=1);

if (! defined('WPINC')) {
    die;
}

// Plugin constants
define('WP_PLUGIN_VERSION', '0.1.0');
define('WP_PLUGIN_DIR', plugin_dir_path(__FILE__));
define('WP_PLUGIN_FILE', __FILE__);

// Load composer autoloader when present
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
}

// Load the plugin bootstrap
if (! class_exists('WpPlugin\\Plugin')) {
    require_once WP_PLUGIN_DIR . 'src/Plugin.php';
}

// Optional: GitHub update checker via yahniselsts/plugin-update-checker
// When the library is installed via Composer, initialize updates from GitHub Releases.
if (class_exists('Puc_v4_Factory')) {
    $updateChecker = Puc_v4_Factory::buildUpdateChecker(
        // Replace with your public repo URL, e.g. https://github.com/owner/wp-plugin
        'https://github.com/terence/wp-plugin',
        WP_PLUGIN_FILE,
        'wp-plugin'
    );
    // If releases are under GitHub Releases, enable release assets.
    $updateChecker->getVcsApi()->enableReleaseAssets();
}

// Activation and deactivation hooks
register_activation_hook(__FILE__, ['WpPlugin\\Plugin', 'activate']);
register_deactivation_hook(__FILE__, ['WpPlugin\\Plugin', 'deactivate']);

/**
 * Start plugin
 */
function wp_plugin_run(): void
{
    $plugin = new WpPlugin\Plugin(WP_PLUGIN_FILE);
    $plugin->run();
}

wp_plugin_run();
