<?php
/**
 * Plugin Name: wp_plugin
 * Plugin URI:  https://example.com/plugins/wp-plugin
 * Description: A lightweight WordPress plugin scaffold (generated by Copilot).
 * Version:     0.1.0
 * Author:      Your Name
 * Author URI:  https://example.com
 * Text Domain: wp-plugin
 * Domain Path: /languages
 * License:     MIT
 */

declare(strict_types=1);

if (! defined('WPINC')) {
    die;
}

// Plugin constants
define('WP_PLUGIN_VERSION', '0.1.0');
define('WP_PLUGIN_DIR', plugin_dir_path(__FILE__));
define('WP_PLUGIN_FILE', __FILE__);

// Load composer autoloader when present
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
}

// Load the plugin bootstrap
if (! class_exists('WpPlugin\\Plugin')) {
    require_once WP_PLUGIN_DIR . 'src/Plugin.php';
}

// Load plugin-update-checker via submodule if not already available through Composer
if (! class_exists('YahnisElsts\\PluginUpdateChecker\\v5\\PucFactory')) {
    $pucFile = __DIR__ . '/vendor/plugin-update-checker/plugin-update-checker.php';
    if (file_exists($pucFile)) {
        require_once $pucFile;
    }
}

// GitHub update checker via plugin-update-checker v5
// Checks GitHub Releases for new versions and provides update information to WordPress.
if (class_exists('YahnisElsts\\PluginUpdateChecker\\v5\\PucFactory')) {
    try {
        $updateChecker = YahnisElsts\PluginUpdateChecker\v5\PucFactory::buildUpdateChecker(
            // Replace with your public repo URL, e.g. https://github.com/owner/wp-plugin
            'https://github.com/terence/wp-plugin',
            WP_PLUGIN_FILE,
            'wp-plugin'
        );
        
        // Enable GitHub Releases - tells the checker to look for release assets (ZIP files)
        if (method_exists($updateChecker, 'getVcsApi')) {
            $updateChecker->getVcsApi()->enableReleaseAssets();
        }
        
        // Optional: Set branch if not using main/master
        // $updateChecker->setBranch('main');
        
        // Optional: For private repos, set authentication token
        // $updateChecker->setAuthentication('your_github_token_here');
    } catch (Exception $e) {
        // Log error but don't break plugin initialization
        error_log('wp-plugin update checker failed: ' . $e->getMessage());
    }
}

// Activation and deactivation hooks
register_activation_hook(__FILE__, ['WpPlugin\\Plugin', 'activate']);
register_deactivation_hook(__FILE__, ['WpPlugin\\Plugin', 'deactivate']);

/**
 * Start plugin
 */
function wp_plugin_run(): void
{
    $plugin = new WpPlugin\Plugin(WP_PLUGIN_FILE);
    $plugin->run();
}

wp_plugin_run();
